<a href="https://colab.research.google.com/github/Rafadiassss/PR-Pao-de-Queijo-Request/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lista 2
Rafaela Dias
TOPICOS 1 E OPITATIVA 1

In [25]:
#Atividade 1
import numpy as np

# Crie seu array
seu_array = np.array([0, 2, 3, 4, 5])

# Verifique se nenhum dos elementos é zero
if np.all(seu_array != 0):
    print("Nenhum dos elementos é zero.")
else:
    print("Pelo menos um elemento é zero.")


Pelo menos um elemento é zero.


In [2]:
#Atividade 2
import numpy as np

# Crie seu array
seu_array = np.array([1, 0, 3, 0, 5])

# Verifique se algum dos elementos é diferente de zero
if np.any(seu_array != 0):
    print("Pelo menos um elemento é diferente de zero.")
else:
    print("Todos os elementos são iguais a zero.")

Pelo menos um elemento é diferente de zero.


In [3]:
#Atividade 3
import numpy as np

# Criar um array de 10 zeros
array_zeros = np.zeros(10)

# Criar um array de 10 uns
array_uns = np.ones(10)

# Criar um array de 10 cincos
array_cincos = np.full(10, 5)

print("Array de 10 zeros:")
print(array_zeros)

print("Array de 10 uns:")
print(array_uns)

print("Array de 10 cincos:")
print(array_cincos)

Array de 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array de 10 uns:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array de 10 cincos:
[5 5 5 5 5 5 5 5 5 5]


In [6]:
#Atividade 4
import numpy as np

# Crie um array de inteiros de 30 a 70
array_inteiros = np.arange(30, 71)

print(array_inteiros)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [7]:
#Atividade 5
import numpy as np

# Crie um array de inteiros pares de 30 a 70
array_pares = np.arange(30, 71, 2)

print(array_pares)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [8]:
#Atividade 6
import numpy as np

# Crie uma matriz identidade 3x3
matriz_identidade = np.identity(3)

print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Atividade 7
import numpy as np

# Gere um número aleatório entre 0 e 1
numero_aleatorio = np.random.rand()

print(numero_aleatorio)

0.7695256500278259


In [10]:
#Atividade 8
import numpy as np

# Gere uma matriz de 15 números aleatórios a partir de uma distribuição normal padrão
matriz_aleatoria = np.random.randn(15)

print(matriz_aleatoria)

[ 1.62846297  0.6246966   0.42624153 -1.01435972 -0.22147855  0.61158341
 -0.30464646  0.93969863  1.25707827 -0.55058968  1.34058994 -0.89404082
  1.21779452 -0.32814825  1.47123172]


In [11]:
#Atividade 9
import numpy as np

# Crie um vetor com valores de 15 a 55
vetor_valores = np.arange(15, 56)

# Imprima todos os valores, exceto o primeiro e o último
print("Vetor original:")
print(vetor_valores)

print("Valores, exceto o primeiro e o último:")
print(vetor_valores[1:-1])

Vetor original:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Valores, exceto o primeiro e o último:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [12]:
#Atividade 10
import numpy as np

# Crie um vetor com valores de 0 a 20
vetor_valores = np.arange(21)

# Altere o sinal dos números no intervalo de 9 a 15
vetor_valores[9:16] *= -1

print(vetor_valores)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [13]:
#Atividade 11
import numpy as np

# Crie um vetor de comprimento 5 com inteiros arbitrários no intervalo de 0 a 10
vetor_arbitrario = np.random.randint(0, 11, 5)

print(vetor_arbitrario)

[ 5  5  6 10  9]


In [14]:
#Atividade 12
import numpy as np

# Vetor 1
vetor1 = np.array([1, 2, 3, 4, 5])

# Vetor 2
vetor2 = np.array([10, 20, 30, 40, 50])

# Multiplicação elemento a elemento dos dois vetores
resultado = vetor1 * vetor2

print(resultado)

[ 10  40  90 160 250]


In [15]:
#Atividade 13
import numpy as np

# Crie uma matriz 3x4 preenchida com valores de 10 a 21
matriz_valores = np.arange(10, 22).reshape(3, 4)

print(matriz_valores)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [16]:
#Atividade 14
import numpy as np

# Criar uma matriz de exemplo
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Encontrar o número de linhas e colunas usando o atributo shape
num_linhas, num_colunas = matriz.shape

# Alternativamente, você pode usar o atributo ndim
# num_linhas = matriz.shape[0]
# num_colunas = matriz.shape[1]

print(f"Número de linhas: {num_linhas}")
print(f"Número de colunas: {num_colunas}")

Número de linhas: 3
Número de colunas: 3


In [17]:
#Atividade 15
import numpy as np

# Crie uma matriz 10x10 preenchida com zeros
matriz = np.zeros((10, 10))

# Defina os elementos nas bordas como 1
matriz[0, :] = 1  # Define a primeira linha para 1
matriz[-1, :] = 1  # Define a última linha para 1
matriz[:, 0] = 1  # Define a primeira coluna para 1
matriz[:, -1] = 1  # Define a última coluna para 1

print(matriz)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
#Atividade 16
import numpy as np

# Defina os dois vetores
vetor1 = np.array([1, 2, 3])
vetor2 = np.array([4, 5, 6])

# Método 1: Use a função np.dot
produto_interno1 = np.dot(vetor1, vetor2)

# Método 2: Use o operador @
produto_interno2 = vetor1 @ vetor2

print(f"Produto Interno (np.dot): {produto_interno1}")
print(f"Produto Interno (@): {produto_interno2}")

Produto Interno (np.dot): 32
Produto Interno (@): 32


In [19]:
#Aividade 17
import numpy as np

# Crie um array de exemplo
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Calcule a soma de todos os elementos
soma_total = np.sum(array)

# Calcule a soma de cada coluna (axis=0)
soma_colunas = np.sum(array, axis=0)

# Calcule a soma de cada linha (axis=1)
soma_linhas = np.sum(array, axis=1)

print("Array:")
print(array)

print(f"Soma de todos os elementos: {soma_total}")
print(f"Soma de cada coluna: {soma_colunas}")
print(f"Soma de cada linha: {soma_linhas}")


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Soma de todos os elementos: 45
Soma de cada coluna: [12 15 18]
Soma de cada linha: [ 6 15 24]


In [20]:
#Atividade 18
import numpy as np

# Crie uma matriz de exemplo
matriz = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Crie um vetor que você deseja adicionar a cada linha
vetor_adicao = np.array([10, 20, 30])

# Use a transmissão (broadcasting) para adicionar o vetor a cada linha
matriz_resultante = matriz + vetor_adicao

print("Matriz original:")
print(matriz)

print("Vetor a ser adicionado a cada linha:")
print(vetor_adicao)

print("Matriz resultante após adição:")
print(matriz_resultante)

Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vetor a ser adicionado a cada linha:
[10 20 30]
Matriz resultante após adição:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [21]:
#Atividade 19
import numpy as np

# Crie duas matrizes de exemplo do mesmo tamanho
matriz1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

matriz2 = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Multiplique as matrizes elemento por elemento
resultado = np.multiply(matriz1, matriz2)

print("Matriz 1:")
print(matriz1)

print("Matriz 2:")
print(matriz2)

print("Resultado da multiplicação elemento por elemento:")
print(resultado)

Matriz 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz 2:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Resultado da multiplicação elemento por elemento:
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [22]:
#Atividade 20
import numpy as np

# Criar um array de exemplo
array = np.array([1, 5, 2, 7, 3, 8, 4, 9, 6])

# Especificar o número de referência
numero_referencia = 5

# Substituir todos os valores iguais a 'numero_referencia' por 0
array_substituido = np.where(array == numero_referencia, 0, array)

# Substituir todos os valores menores que 'numero_referencia' por -1
array_substituido = np.where(array_substituido < numero_referencia, -1, array_substituido)

# Substituir todos os valores maiores que 'numero_referencia' por 1
array_substituido = np.where(array_substituido > numero_referencia, 1, array_substituido)

print("Array original:")
print(array)

print("Array após a substituição:")
print(array_substituido)

Array original:
[1 5 2 7 3 8 4 9 6]
Array após a substituição:
[-1 -1 -1  1 -1  1 -1  1  1]


In [23]:
#Atividade 21
import numpy as np

# Criar um array de exemplo
array = np.array([[3, 2, 1],
                  [6, 5, 4],
                  [9, 8, 7]])

# Ordenar ao longo do primeiro eixo (linhas)
sorted_axis_0 = np.sort(array, axis=0)

# Ordenar ao longo do último eixo (colunas)
sorted_axis_1 = np.sort(array, axis=-1)

# Ordenar o array achatado
sorted_flatten = np.sort(array.ravel())

print("Array original:")
print(array)

print("Array ordenado ao longo do primeiro eixo (linhas):")
print(sorted_axis_0)

print("Array ordenado ao longo do último eixo (colunas):")
print(sorted_axis_1)

print("Array achatado ordenado:")
print(sorted_flatten)


Array original:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
Array ordenado ao longo do primeiro eixo (linhas):
[[3 2 1]
 [6 5 4]
 [9 8 7]]
Array ordenado ao longo do último eixo (colunas):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array achatado ordenado:
[1 2 3 4 5 6 7 8 9]
